version: 2

- package-ecosystem: npm
  directory: "/"
  schedule:
      interval: monthly
  assignees:
      - "orkhanahmadov"
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
      interval: monthly
  assignees:
      - "orkhanahmadov"
  open-pull-requests-limit: 10
